# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Minecraft/NeoForge versions
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.86
neo_version_range=[21.1,)
loader_version_range=[4,)

# Parchment mappings (optional, for better parameter names)
parchment_minecraft_version=1.21
parchment_mappings_version=2024.07.28

# Mod properties
mod_id=rats
mod_name=Rats
mod_license=GNU LESSER GENERAL PUBLIC LICENSE
mod_version=8.1.3
mod_authors=AlexThe666
mod_description=What are we going to do today Pinky?

# JEI (optional, for recipe viewing)
jei_version=19.21.0.247
