package com.github.alexthe666.rats;

import net.minecraftforge.fml.config.ModConfig;

public class RatConfig {
    public static boolean spawnRats = true;
    public static boolean ratsDespawn = true;
    public static boolean spawnPiper = true;
    public static int ratSpawnRate = 80;
    public static int ratSpawnDecrease = 5;
    public static int piperSpawnDecrease = 1;
    public static int piperSpawnRate = 6;
    public static float piperHatDropRate = 0.09F;
    public static float archeologistHatSpawnRate = 0.12F;
    public static float ratlanteanAutomatonHealth = 600F;
    public static float ratlanteanAutomatonAttack = 6F;
    public static float neoRatlanteanHealth = 300F;
    public static float neoRatlanteanAttack = 8F;
    public static float dutchratHealth = 400F;
    public static float dutchratAttack = 8F;
    public static boolean ratsSpawnLikeMonsters = true;
    public static boolean cheesemaking = true;
    public static boolean plagueRats = true;
    public static int milkCauldronTime = 150;
    public static boolean ratsDigBlocks = true;
    public static boolean ratsBreakCrops = true;
    public static boolean ratsStealItems = true;
    public static boolean ratsContaminateFood = true;
    public static boolean golemsTargetRats = true;
    public static boolean villagePetShops = true;
    public static boolean villageGarbageHeaps = true;
    public static boolean villagePlagueDoctors = true;
    public static boolean disablePlastic = false;
    public static boolean ratsBreakBlockOnHarvest = true;
    public static boolean plagueSpread = true;
    public static boolean plagueHearts = true;
    public static float ratStrengthThreshold = 4.0F;
    public static int ratFluteDistance = 2;
    public static int ratCageCramming = 4;
    public static int ratUpdateDelay = 100;
    public static int tokenDropRate = 10000;
    public static String[] blacklistedRatBlocks = new String[0];
    public static int[] blacklistedRatDimensions = new int[0];
    public static boolean disableRatlantis = false;
    public static int ratlantisDimensionId = -8;
    public static int ratlantisPortalExitDimension = 0;
    public static int maxDestroyedLeaves = 10000;
    public static float blackDeathHealth = 400F;
    public static float blackDeathAttack = 4F;
    public static double ratDespawnFarDistance = 144F;
    public static double ratDespawnCloseDistance = 32F;
    public static int ratDespawnRandomChance = 800;
    public static boolean ratFartNoises = true;
    public static int ratRFTransferBasic = 100;
    public static int ratRFTransferAdvanced = 500;
    public static int ratRFTransferElite = 1000;
    public static int ratRFTransferExtreme = 100000;
    public static double ratVoodooDistance = 32;
    public static boolean addLoot = true;
    public static int defaultRatRadius = 16;
    public static int maxRatRadius = 32;
    public static double garbageSpawnRate = 0.15F;

    public static void bakeClient(final ModConfig config) {
        plagueHearts = ConfigHolder.CLIENT.plagueHearts.get();
    }

    public static void bakeServer(final ModConfig config) {
         spawnRats = ConfigHolder.SERVER.spawnRats.get();
         ratsDespawn = true;
         spawnPiper = ConfigHolder.SERVER.spawnPiper.get();
         ratSpawnRate = ConfigHolder.SERVER.ratSpawnRate.get();
         ratSpawnDecrease = ConfigHolder.SERVER.ratSpawnDecrease.get();
         piperSpawnDecrease = ConfigHolder.SERVER.piperSpawnDecrease.get();
         piperSpawnRate = ConfigHolder.SERVER.piperSpawnRate.get();
         piperHatDropRate = ConfigHolder.SERVER.piperHatDropRate.get().floatValue();
         archeologistHatSpawnRate = ConfigHolder.SERVER.archeologistHatSpawnRate.get().floatValue();
         ratlanteanAutomatonHealth = ConfigHolder.SERVER.ratlanteanAutomatonHealth.get().floatValue();
         ratlanteanAutomatonAttack = ConfigHolder.SERVER.ratlanteanAutomatonAttack.get().floatValue();
         neoRatlanteanHealth = ConfigHolder.SERVER.neoRatlanteanHealth.get().floatValue();
         neoRatlanteanAttack = ConfigHolder.SERVER.neoRatlanteanAttack.get().floatValue();
         dutchratHealth = ConfigHolder.SERVER.dutchratHealth.get().floatValue();
         dutchratAttack = ConfigHolder.SERVER.dutchratAttack.get().floatValue();
         ratsSpawnLikeMonsters = ConfigHolder.SERVER.ratsSpawnLikeMonsters.get();
         cheesemaking = ConfigHolder.SERVER.cheesemaking.get();
         plagueRats = ConfigHolder.SERVER.plagueRats.get();
         milkCauldronTime = ConfigHolder.SERVER.milkCauldronTime.get();
         ratsDigBlocks = ConfigHolder.SERVER.ratsDigBlocks.get();
         ratsBreakCrops = ConfigHolder.SERVER.ratsBreakCrops.get();
         ratsStealItems = ConfigHolder.SERVER.ratsStealItems.get();
         ratsContaminateFood = ConfigHolder.SERVER.ratsContaminateFood.get();
         golemsTargetRats = ConfigHolder.SERVER.golemsTargetRats.get();
         villagePetShops = ConfigHolder.SERVER.villagePetShops.get();
         villageGarbageHeaps = ConfigHolder.SERVER.villageGarbageHeaps.get();
         villagePlagueDoctors = ConfigHolder.SERVER.villagePlagueDoctors.get();
         disablePlastic = ConfigHolder.SERVER.disablePlastic.get();
         ratsBreakBlockOnHarvest = ConfigHolder.SERVER.ratsBreakBlockOnHarvest.get();
         plagueSpread = ConfigHolder.SERVER.plagueSpread.get();
         ratStrengthThreshold = ConfigHolder.SERVER.ratStrengthThreshold.get().floatValue();
         ratFluteDistance = ConfigHolder.SERVER.ratFluteDistance.get();
         ratCageCramming = ConfigHolder.SERVER.ratCageCramming.get();
         ratUpdateDelay = ConfigHolder.SERVER.ratUpdateDelay.get();
         tokenDropRate = ConfigHolder.SERVER.tokenDropRate.get();
         disableRatlantis = ConfigHolder.SERVER.disableRatlantis.get();
         ratlantisDimensionId = ConfigHolder.SERVER.ratlantisDimensionId.get();
         ratlantisPortalExitDimension = ConfigHolder.SERVER.ratlantisPortalExitDimension.get();
         maxDestroyedLeaves = ConfigHolder.SERVER.maxDestroyedLeaves.get();
         blackDeathHealth = ConfigHolder.SERVER.blackDeathHealth.get().floatValue();
         blackDeathAttack = ConfigHolder.SERVER.blackDeathAttack.get().floatValue();
         ratDespawnFarDistance = ConfigHolder.SERVER.ratDespawnFarDistance.get();
         ratDespawnCloseDistance = ConfigHolder.SERVER.ratDespawnCloseDistance.get();
         ratDespawnRandomChance = ConfigHolder.SERVER.ratDespawnRandomChance.get();
         ratFartNoises = ConfigHolder.SERVER.ratFartNoises.get();
         ratRFTransferBasic = ConfigHolder.SERVER.ratRFTransferBasic.get();
         ratRFTransferAdvanced = ConfigHolder.SERVER.ratRFTransferAdvanced.get();
         ratRFTransferElite = ConfigHolder.SERVER.ratRFTransferElite.get();
         ratRFTransferExtreme = ConfigHolder.SERVER.ratRFTransferExtreme.get();
         ratVoodooDistance = ConfigHolder.SERVER.ratVoodooDistance.get();
         addLoot = ConfigHolder.SERVER.addLoot.get();
         defaultRatRadius = ConfigHolder.SERVER.defaultRatRadius.get();
         maxRatRadius = ConfigHolder.SERVER.maxRatRadius.get();
        garbageSpawnRate = ConfigHolder.SERVER.garbageSpawnRate.get();
    }
}
